package Dingler::Model::DinglerWeb;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'DinglerWeb::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=dingweb',
        user => '',
        password => '',
        pg_enable_utf8 => q{1},
    }
);

=head1 NAME

Dingler::Model::DinglerWeb - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Dingler>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<DinglerWeb::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.49

=head1 AUTHOR

Frank Wiegand

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
