package Dingler::Model::Ticket;
use parent 'Catalyst::Model::DBIC::Schema';

use warnings;
use strict;

__PACKAGE__->config(
    schema_class => 'Dingler::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:db/ticket.db',
        user => '',
        password => '',
        sqlite_unicode => 1,
    }
);

1;
__END__

=head1 NAME

Dingler::Model::Ticket - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Dingler>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Dingler::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.41

=head1 AUTHOR

Frank Wiegand

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
